### ISSUE TITLE
Cuff script not showing cuffing

### ISSUE THREAD

**Issue by toddpiekutowski1** [Sc0ttM/SEM_InteractionMenu#11]
Will attempt to cuff a player, but the cuffs will not show up. Player will be 'cuffed' (can't steer a car or use weapons) but no cuffs will show up on the ped.

**Comment by Sc0ttM** [comment]
Thank you for reporting this, I will look into this issue when I'm next available and see if I can get a fix pushed!

**Comment by Sc0ttM** [comment]
As some changes have been made to the cuffing section, could you verify that any issues you have had are currently fixed
