### ISSUE TITLE
Unracking Weapons

### ISSUE THREAD

**Issue by radiusdevelop** [Sc0ttM/SEM_InteractionMenu#12]
So, found this bug just messing around but when I unrack my rifle or shotgun and I try to put it away..it doesn't go away. Maybe it's something easy I can fix but yeah.

**Comment by HaroldFinch5M** [comment]
Hey, just a suggestion you can make that part taken out because I see that it doesn't work all the time for the server I am a developer for so I just took out the unrack script of it.

**Comment by Sc0ttM** [comment]
As the new update changed the way in which the weapon rack/unrack worked, any issues should be fixed - if you could verify and get back to me to confirm
