### ISSUE TITLE
Does Not Specify an fx_version

### ISSUE THREAD

**Issue by thinksgamingyt** [Sc0ttM/SEM_InteractionMenu#14]
Updated to version 1.6 and its saying the error below

![Capture](https://user-images.githubusercontent.com/37827771/93852129-cc6aea00-fcf4-11ea-9cb8-0c660b8c282b.PNG)

**Comment by Sc0ttM** [comment]
If you head to [here](https://semdevelopment.com/releases/interactionmenu/docs/faq) and checkout **SEM_InteractionMenu doesn't specify an 'fx_version'** that will help you
