### ISSUE TITLE
Traffic Manager

### ISSUE THREAD

**Issue by OfficerDonut324** [Sc0ttM/SEM_InteractionMenu#15]
While using the Traffic Manager and set up a radius like 10-100 meters, and just walks a few meters down the road. All AIs just ignores the script and drives like nothing can stop them. They stop only when you're near an AI car but if you walk they just keep going.

**Comment by Sc0ttM** [comment]
This was never reported to me during testing, I will look into this and get back to you.

**Comment by Sc0ttM** [comment]
After testing, on a localhost server along with multiple beta testers also testing the resource and this feature, no issues were reported

**Comment by LightisSpace** [comment]
I am having the problem where the Traffic Manger doesn't want to work and this is happening to all of the members of my community as well.
