### ISSUE TITLE
Props Not being server sided.

### ISSUE THREAD

**Issue by LukeM03** [Sc0ttM/SEM_InteractionMenu#17]
The props thru the LEO menu's. The Props are not visible to everyone in the server.  This just seems to be with the new Update. Also there is a glitch when you are in a car you can't access the menu. My key is F5. I am usually more active in discord so message me @Luke M#0001

**Comment by Lxk3y** [comment]
Can confirm 1.6 and 1.6.1 both contain this issue where props dont sync

**Comment by Sc0ttM** [comment]
Thanks for the report, we'll look into why the new update caused this issue.

**Comment by Sc0ttM** [comment]
With update **v1.6.2** the issue relating to the props not being seen by others should be fixed if you could verify that it would be appreciated.
