### ISSUE TITLE
You can't uncuff you or others // If you type /drag [yourID] your game crashes.

### ISSUE THREAD

**Issue by VioletSnow08** [Sc0ttM/SEM_InteractionMenu#2]
I can't seem to uncuff my friend or myself and vice-versa with him. I also did /drag [myID] and it broke my game

**Comment by Sc0ttM** [comment]
The issue regarding the inability to uncuff people has been found and will be resolved in the next update of the resource!

**Comment by Sc0ttM** [comment]
Release **v1.5** fixes the inability to uncuff people along with fixing `/drag` crashing the player
