### ISSUE TITLE
/cuff /drag don't work

### ISSUE THREAD

**Issue by Scotts-Totts** [Sc0ttM/SEM_InteractionMenu#20]
Both /cuff and /drag are non-functional. 
![image](https://user-images.githubusercontent.com/69021545/99478232-04bc2c80-2922-11eb-82e5-349b0b7de605.png)
This is the applicable part of the config and when performed in game it returns the "Player too far away" error message.

**Comment by Sc0ttM** [comment]
If you could open a ticket on our support [Discord](https://semdevelopment.com/discord) using `!ticket` I will help you over there quicker than over here on GitHub

**Comment by Sc0ttM** [comment]
This issue has been fixed and will appear in the next update for the resource, in the meantime I will add the fixed code below.


`functions.lua` **Line 75**
```
function GetDistance(ID)
    local Ped = GetPlayerPed(-1)
    local Ped2 = GetPlayerPed(GetPlayerFromServerId(ID))
    return GetDistanceBetweenCoords(GetEntityCoords(Ped), GetEntityCoords(Ped2), true)
end
```
