### ISSUE TITLE
Spike Strips

### ISSUE THREAD

**Issue by RealZotty** [Sc0ttM/SEM_InteractionMenu#24]
When i place spikes and go barley away from them it wont let me remove the spikes anymore

**Comment by Sc0ttM** [comment]
How far away would you say you moved before being unable to remove them?

**Comment by RealZotty** [comment]
At first it only happened when i went far away which i get but then it
started to happen after 10 mins if im right next to them or even if i go 10
meters down the road

**Comment by Sc0ttM** [comment]
This issue doesn't occur even when teleported across the map, what version are you using?

**Comment by RealZotty** [comment]
On the console it says im up to date with the latest version.7

**Comment by Sc0ttM** [comment]
Did you update to **v1.7** or download it?
If you updated to that version did you update all the files when you did?

**Comment by RealZotty** [comment]
Fresh install, new cfg file and everything

**Comment by Sc0ttM** [comment]
I apologise for the delay in responding!
Are you using OneSync?

**Comment by RealZotty** [comment]
Yes, infinity

**Comment by Sc0ttM** [comment]
Alright, I'm working with someone rn in our Discord as there seems to be an issue with props/spikes with OneSync.
When I have anything further I'll let you know!

**Comment by RealZotty** [comment]
Alrighty, Thanks.
