### ISSUE TITLE
ace perms not working

### ISSUE THREAD

**Issue by MillieMods** [Sc0ttM/SEM_InteractionMenu#29]
ive put the ace perms but it still lets everyone see the LEO and FIRE toolbox

**Comment by Sc0ttM** [comment]
Setting the ACE perms in your `server.cfg` is only the first step, you need to head into the `config.lua` and look for **Config.LEOAccess** [here](https://github.com/Sc0ttM/SEM_InteractionMenu/blob/master/config.lua#L151) and change that you `4`
