### ISSUE TITLE
Im getting this error

### ISSUE THREAD

**Issue by Irishgarda** [Sc0ttM/SEM_InteractionMenu#31]
![image](https://user-images.githubusercontent.com/77333848/144424798-75b7ae11-13b6-4bd4-9265-5a9b0bcace0a.png) [ in game console]

Hi i am getting this error in the in game console the only this i have changed in the config file is the locations of the hospitals, here is what i changed 
![image](https://user-images.githubusercontent.com/77333848/144425028-85d9bab7-1314-4ae1-a046-992d46da1a1d.png)
when i go to the server console i am getting this error 
![image](https://user-images.githubusercontent.com/77333848/144425177-bf3e7e8f-036b-447a-a668-e72a5be7deb1.png)

**Comment by Sc0ttM** [comment]
Hey so the interaction menu currently doesn't support that format similar to the jail feature.
Currently the hospital config only allows ONE set of coords like [this](https://github.com/Sc0ttM/SEM_InteractionMenu/blob/master/config.lua#L371) and that's why you are getting that error

**Comment by Irishgarda** [comment]
so if i take out the sandyshore hosptial it should get rid of that error

**Comment by Sc0ttM** [comment]
yes, the hospital locations need to be formatted like
`{name = 'Sandy Shores', coords = {x = 1839.13, y = 3673.26, z = 34.27 , h = 210.83}},`
without the `Hospital` and `Release` values

**Comment by Irishgarda** [comment]
i copied your format and this is the error im getting 
![image](https://user-images.githubusercontent.com/77333848/144662907-5cefcaf2-2343-43c7-97ef-f76fdf21bacc.png)

**Comment by Sc0ttM** [comment]
can you show me what you put?

**Comment by Irishgarda** [comment]
so sorry for the late reply and so sorry if i done this wrong this is is what i done 
![image](https://user-images.githubusercontent.com/77333848/144702224-8fb76fe5-6477-4398-9978-f85639f4ed5f.png)

**Comment by Sc0ttM** [comment]
you'll need to remove the `['Pillbox Hill']` and the `['Paleto Bay']` for it to work

**Comment by Irishgarda** [comment]
So i cant have the three of them just one is it???

**Comment by Sc0ttM** [comment]
no, but you'll need to change them to the same formatting as the Sandy Shores one
