### ISSUE TITLE
Issue With Order Of Vehicle Categories And zIndex

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [Sc0ttM/SEM_InteractionMenu#32]
Hello friends, two questions!

1) How do I order the categories under Vehicles in the Interaction Menu? I can't seem to figure out how its organizing the order.

2) Is there a way that I can place the menu zindex higher. As you see the money is on top. 

Thanks!
![image](https://user-images.githubusercontent.com/25211271/145486940-b015b369-f090-4665-9b01-ce7581bc0139.png)

**Comment by Kayne64** [comment]
Maybe Move the Money HUD, You should just be able to do it in Order?

**Comment by Sc0ttM** [comment]
With the current menu, its not possible to order the vehicle menu in the way you are looking for.
