### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LongDaysYT** [Sc0ttM/SEM_InteractionMenu#33]
So in a popular server i used to play on they had the "SEM_InteractionMenu" but when i became a whitelisted LEO i could see the LEO only when i typed onduty but i can not figure out how to do that with my own server

**Comment by Kayne64** [comment]
still need help?

**Comment by LongDaysYT** [comment]
> still need help?

yes i do

**Comment by LongDaysYT** [comment]
> still need help?

could you help me?

**Comment by Sc0ttM** [comment]
Look at `Conifg.LEOAccess`, there you can change who can access the menu and if you choose ACE permissions you will need `sem_intmenu.leo` to be able to access it

**Comment by LongDaysYT** [comment]
> Look at `Conifg.LEOAccess`, there you can change who can access the menu and if you choose ACE permissions you will need `sem_intmenu.leo` to be able to access it

so if im ingame i cant see it unless i type onduty?
with ace perms

**Comment by Sc0ttM** [comment]
No, it is one or the other with the current version. You can NOT use both atm, without editing the resource.
