### ISSUE TITLE
When the shield is toggled it does not act like a shield

### ISSUE THREAD

**Issue by Kaleb99jOfficial** [Sc0ttM/SEM_InteractionMenu#37]
When I toggle the shield it is not held by the character like a shield. Removing and re-adding the resource did not fix this. See the images below to see the issue
![20220618151113_1](https://user-images.githubusercontent.com/73747982/174453172-848d6673-11a1-43a7-9777-b5da6103467e.jpg)
![20220618151108_1](https://user-images.githubusercontent.com/73747982/174453174-7239aed0-1b22-47f5-8167-115302ad2e76.jpg)
.

**Comment by SimbbaDev** [comment]
You would have to toggle the shield, Pull out your weapon. Then pull toggle the shield. This is because I believe the holster animation occurs after the toggle shield because its trying to pull out a weapon then stops the script.

**Comment by Sc0ttM** [comment]
If another animation occurs, like said above a holster animation this would mess up the position/look of the shield. A weapon should be automatically given to you when the toggle the shield.

**Comment by Kaleb99jOfficial** [comment]
> If another animation occurs, like said above a holster animation this would mess up the position/look of the shield. A weapon should be automatically given to you when the toggle the shield.

I completely forgot that I submitted an issue. We later tested without the holster animation and determined it to be the cause. We have since removed the holster animation.
