### ISSUE TITLE
Password Issue

### ISSUE THREAD

**Issue by DillonB54** [Sc0ttM/SEM_InteractionMenu#4]
When you start the script with your server any password you put in including the right one it says incorrect password. Then when you restart it, it works.
To replicate turn password on in config and set it.

**Comment by DillonB54** [comment]
![1](https://user-images.githubusercontent.com/64702271/81991243-28bb5000-9617-11ea-90db-275f7655b88e.PNG)

**Comment by Sc0ttM** [comment]
We are aware of this issue and are trying to find the root cause.
I will post additional information when I know more and/or a fix to the issue.

**Comment by Sc0ttM** [comment]
@DillonB54 As I personally don't have this issue and my Beta Testers haven't had this issue, if you haven't already could you join our [Discord](https://semdevelopment.com/discord) and open a support ticket using `!ticket` so I can help you further & get additional information from you. 

*Once you have created the support ticket mention you are from this issue*

**Comment by Sc0ttM** [comment]
This issue hasn't been able to be replicated by SEM Developers or Beta Testers. The image provided doesn't match the output of which the resource gives when an invalid password is used.
