### ISSUE TITLE
Skips over peds & loadouts most of the time

### ISSUE THREAD

**Issue by matei0906** [Sc0ttM/SEM_InteractionMenu#6]
When I want to spawn a ped or weapon loadout, most of the time it skips over a ped or loadout, and it takes multiple tries to get the right ped or loadout

**Comment by Sc0ttM** [comment]
In an update a while back I reduced the time between it switching the items, I will increase the time even more in the next update to see if this helps.

**Comment by Sc0ttM** [comment]
I've increased the time in which it takes to switch items, hopefully this helps. If you could let me know if it does or doesn't help!

**Comment by Sc0ttM** [comment]
No Verification, Issue Closed
