### ISSUE TITLE
Traffic manager

### ISSUE THREAD

**Issue by frazz1234** [Sc0ttM/SEM_InteractionMenu#7]
Traffic manager is broken, impossible to change de size of the cercle... need to restart the ressources 

Its could be possible to do something like trafficmanager ?? more frendly user !! 

Thanks

**Comment by Sc0ttM** [comment]
The reason why you can change the size is so the officer on a scene can determine what would be a good size to manage the traffic, compared to having one set size.

Could you be more specific on your issue;
does the list not change?
when a size is selected does it do another size?
the traffic don't stop/slow?
the circles on the map don't appear?

What exactly is "broken"?

**Comment by frazz1234** [comment]
Impossible to move the size off the cercle...  sometime works.. and sometimes not. 

Need to restart the ressource for work.....ok but not very well

**Comment by Sc0ttM** [comment]
NativeUI has an issue where sometimes it skips items in a list.
I have increased the time in which it takes to move to prevent this (In a past update), I will increase this further in an update to see if that helps.

**Comment by Sc0ttM** [comment]
I've increased the time in which it takes to switch items, hopefully this helps. If you could let me know if it does or doesn't help!

**Comment by Sc0ttM** [comment]
No Verification, Issue Closed
