### ISSUE TITLE
Searching not working.

### ISSUE THREAD

**Issue by mgflames** [Sc0ttM/SEM_InteractionMenu#8]
If a civilian sets their inventory using Civ Toolbox > Inventory and then someone goes to LEO Toolbox > Actions > Inventory to search them, it says "Searching ... Inventory Items: Empty."

![unknown](https://user-images.githubusercontent.com/19205814/83818218-ade9d000-a6be-11ea-8ae2-3e837695bcd0.png)

**Comment by mgflames** [comment]
This also occurs with BAC.

**Comment by frazz1234** [comment]
Same for me and breathalizer to !

**Comment by Sc0ttM** [comment]
We are aware of this issue, a fix has been found and requires testing to be sure.
It will be released soon in an update!

**Comment by Sc0ttM** [comment]
This is fixed in the newest version **v1.5.1**
